### ISSUE TITLE
You run foul of Terry, sir.

### ISSUE THREAD

**Issue by emansom** [ZenithOS/ZenithOS#5]
He would never approve of networking stacks within it's temple. Networked systems would only allow the enemy to take hold. May CIA goons forever glow in the dark.

**Comment by Midnoclose** [comment]
If you don't like it use vanilla TempleOS, this is an issue tracker for bugs and feature requests.

**Comment by TomAwezome** [comment]
The power is in your hands to use the full extent of ZenithOS without the network stack. You have the power to install ZenithOS, and upon booting, delete the Net directory, located in the Home folder. It is not included as part of the kernel (unlike Shrine...) so you are free to never use it.

I would suggest you create an Issue on the Shrine repository, and suggest to them they remove the networking stack from the kernel, so that users are not forced to use networking.
