### ISSUE TITLE
AHCI: Could not find ATAPI boot drive

### ISSUE THREAD

**Issue by ThuleanTraveller** [ZenithOS/ZenithOS#7]
I'm trying to run ZenithOS natively on a T61 Thinkpad. I've been able to run live CD's and install both vanilla TempleOS and ShrineOS using this disk drive (H.L Data Storage GSA-4083N) the BIOS boot menu labels it as ATAPI, but once Zenith starts, it gives the error message "AHCI: Drive is not an ATAPI drive!"

Happy to give any further information.
![DSC_0223](https://user-images.githubusercontent.com/80014348/123316396-b066d400-d524-11eb-9a4c-3bf8cf779295.JPG)

**Comment by TomAwezome** [comment]
The error message you got was due to the boot process not stopping when no ATAPI drives were found. On boot, it only saw a drive with signature 0x101 (ATA), and an empty port. It reported the ATA drive as an ATAPI drive erroneously, I just committed a fix for that. I'm not sure why it isn't recognizing the ATAPI drive.

**Comment by TomAwezome** [comment]
![screen05](https://user-images.githubusercontent.com/10574504/123355959-b82e7480-d534-11eb-9575-c95c77da5eb4.jpg)
IDE drives are not supported. ZenithOS only supports SATA ATA/ATAPI drives.
